### ISSUE TITLE
Create docs for config options

### ISSUE THREAD

**Issue by ekmartin** [ekmartin/slack-irc#113]
The example in the README is kind of unstructured, should have a proper markdown document or similar describing each option.

**Comment by philliproso** [comment]
I actually prefer this style of inline documentation, it breaks the "RULES" but is actually very easy to use. My mind does not need to context switch between code reading and doc reading. I can just directly copy and paste and change stuff. I dont have to just scroll down for the code sample like I do anyway. 

In short I might make similar comments on another github repo. 
_For such a simple parameter set why not just inline the descriptions as comments in the code sample instead of providing such verbose auto-generated space wasting table stuff._

**Comment by ekmartin** [comment]
That's good to hear. It definitely wouldn't need a huge auto generated thing (like readthedocs or similar). Might be that the best solution would just be to split the current config into two sections though - one for the simple one and one for the more advanced example (think that's a confusing point for some new users at the moment).

Closing this though, thanks for the feedback.
