### ISSUE TITLE
How do I know what to use for Token? Mapping?

### ISSUE THREAD

**Issue by s3w47m88** [ekmartin/slack-irc#211]
Forgive my ignorance, but I'm using an IRC for the first time in Ubuntu 17.04 + GNOME 3.24. I'm trying to connect my IRC Channels to Slack via `slack-irc` but I'm unclear as to where I should generate a token from and what I'm mapping.

I don't see any documentation in the readme or Wiki for this that tell me:

1. Where do I generate a Token from?
2. What is the purpose of generating a Token?
3. What is Mapping in the configuration file used for?

Thank you. Again, I apologize if this is not the correct outlet to post this question or if my question is invalidly formed.

**Comment by ekmartin** [comment]
The token is for a bot user, so that slack-irc can receive and send messages on the Slack you want to bridge. More info about bot users and how to create one (which will also give you a token) can be found here: https://api.slack.com/bot-users

The channel mapping is used to know which Slack channel is connected to which IRC channel. So if you have a channel named #general you want to bridge to an IRC channel named #talk you'd put something like `"#general": "#talk"` in your mapping.

**Comment by s3w47m88** [comment]
Ok thank you!
