### ISSUE TITLE
Mirror slack attachments to IRC

### ISSUE THREAD

**Issue by matschaffer** [ekmartin/slack-irc#22]
Looks like attachments (e.g., a png) in slack don't cause any kind of IRC notification. Granted, you'd probably need a slack account to see it, but might be good to at least provide some notification that it happened incase people want to get a slack account to see it.

**Comment by matschaffer** [comment]
Oh, after poking a bit this may be a limitation of the slack api.

https://api.slack.com/rtm reads "The RTM API only supports posting simple messages formatted using our default message formatting mode. It does not support attachments or other message formatting modes. "

Since slack-client appears to be using the RTM API this may just not be feasible.

**Comment by ekmartin** [comment]
Would be cool, but as you mentioned Slack's RTM API doesn't send any info about attachments at the moment. slack-irc used incoming/outgoing integrations [previously](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#300---2015-03-24), which would've made it possible. However this made it quite painful to have multiple channels, since you'd need one outgoing integration per channel, versus just needing one bot user per slack-irc instance.

I'll keep this open in case Slack adds support for attachments in the RTM API.

**Comment by ekmartin** [comment]
Actually, Slack does send info about posted files, it's just not sent with a message event. Instead uploaded files result in their own event type, like this one: https://api.slack.com/events/file_shared

It doesn't seem like node-slack-client [does anything](https://github.com/slackhq/node-slack-client/blob/master/src%2Fclient.coffee#L513) with the events at the moment though, but I'll investigate.
