### ISSUE TITLE
Beware of case-sensitivity in IRC channel names

### ISSUE THREAD

**Issue by ryanturner** [ekmartin/slack-irc#31]
Disregard, I guess. Still trying to sort out if this is an issue or not.

**Comment by ekmartin** [comment]
As far as I know IRC channel names are case insensitive, but there seems to be an issue with case sensitivity and messages from IRC -> Slack. Probably because the names are lowercase when they come from IRC [here](https://github.com/ekmartin/slack-irc/blob/5c99b8c0fd3ed6cb770786437d21f005f6528ae2/lib/bot.js#L152), while the name might have uppercase characters in your channel mapping. Should probably just lowercase all channel names in the channel mapping automatically and it wouldn't be a problem, will look into it.

As a workaround I don't think there's any issues if you just have lowercase channel names in your mapping, as there shouldn't be a difference between the IRC channel #channel and #CHANNEL.

**Comment by ekmartin** [comment]
This should have been fixed in 3.3.1 :)
