### ISSUE TITLE
Custom emoji support

### ISSUE THREAD

**Issue by matschaffer** [ekmartin/slack-irc#35]
Could be good to allow emoji extension to cover emoji that are posted to a given slack org.

Maybe something nested under the config?

**Comment by ekmartin** [comment]
Aren't most custom emojis stuff that don't really translate that well to text based emojis anyway though? I.e. if you have an emoji named :supershipit:, wouldn't the actual textual name be the most descriptive?

The config already has quite a few options, and since what slack-irc does really isn't that complicated I'm interested in keeping it as a minimal as possible. What do you think?

**Comment by matschaffer** [comment]
We have a custom heart `:lt3:` that we were thinking of also translating to <3

Not exactly a huge use-case but seemed worth asking. Maybe I'll try it on our end first, see how it goes and send a PR if the use-case expands.

**Comment by ekmartin** [comment]
Closing this for now. I could see it being useful, but I'm not sure if it'd be worth the added complexity in terms of trying to keep slack-irc as compact as possible.
