### ISSUE TITLE
Config file clarification 

### ISSUE THREAD

**Issue by jasonbio** [ekmartin/slack-irc#69]
Maybe it's just because I'm tired, but it took me a long time to figure out that if you're only defining one bot in the config file, don't forget to take it out of the object brackets that the example includes. For example:

```js
{
    "nickname": "test2",
    "server": "irc.testbot.org",
    "token": "slacktoken2",
    "channelMapping": {
      "#other-slack": "#new-irc-channel"
    }
}
```

instead of 

```js
[
  {
    "nickname": "test2",
    "server": "irc.testbot.org",
    "token": "slacktoken2",
    "channelMapping": {
      "#other-slack": "#new-irc-channel"
    }
  }
]
```

Maybe a little wiki clarification? If not, at least this is documented so some poor soul doesn't pull their hair out all night.

**Comment by ekmartin** [comment]
Hi! Were you looking at the example on the wiki? I've removed it now, as it hasn't been kept up to date, like the one in the README, here: https://github.com/ekmartin/slack-irc#example-configuration 

If you have any suggestions towards making it more readable they're more than welcome.

I think you may have met some other issue while testing though, because having array brackets around a single configuration will work just the same as without them. Do you have an error output I can look at?

**Comment by jasonbio** [comment]
Funny enough I cannot reproduce the error anymore. You can probably close this :)

**Comment by ekmartin** [comment]
Glad you got it working, feel free to reopen if you manage to reproduce the error later.
